<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="3.5">
  <PropertyGroup>
    <TargetFrameworkVersion>v3.5</TargetFrameworkVersion>
	<OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="*.cs" />
    <Compile Include="communication\topology\*.cs" />
    <Compile Include="communication\protocol\*.cs" />
  </ItemGroup>
  <Target Name="Build">
    <Csc Sources="@(Compile)" />
  </Target>
</Project>