.TH "general Directory Reference" 3 "Wed Jun 19 2013" "Sharerd-Printing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
general Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcommunication\fP"
.br
.ti -1c
.RI "directory \fBProperties\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAComputer\&.cs\fP"
.br
.ti -1c
.RI "file \fBComputer\&.cs\fP"
.br
.ti -1c
.RI "file \fBIApplication\&.cs\fP"
.br
.ti -1c
.RI "file \fBIPrinter\&.cs\fP"
.br
.ti -1c
.RI "file \fBIPrintTask\&.cs\fP"
.br
.ti -1c
.RI "file \fBPrinter\&.cs\fP"
.br
.ti -1c
.RI "file \fBPrintTask\&.cs\fP"
.br
.in -1c
