.TH "general/communication Directory Reference" 3 "Wed Jun 19 2013" "Sharerd-Printing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
general/communication Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBprotocol\fP"
.br
.ti -1c
.RI "directory \fBtopology\fP"
.br
.in -1c
