.TH "general.IProtocol< Ttransfertype >" 3 "Wed Jun 19 2013" "Sharerd-Printing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
general.IProtocol< Ttransfertype > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBgeneral\&.ProtocolSoap< Ttransfertype >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBconnect\fP (Ttransfertype obj, string url)"
.br
.ti -1c
.RI "void \fBdisconnect\fP ()"
.br
.ti -1c
.RI "bool \fBsend\fP (Ttransfertype obj)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool general\&.IProtocol< Ttransfertype >\&.connect (Ttransfertypeobj, stringurl)"

.PP
Implemented in \fBgeneral\&.ProtocolSoap< Ttransfertype >\fP\&.
.SS "void general\&.IProtocol< Ttransfertype >\&.disconnect ()"

.PP
Implemented in \fBgeneral\&.ProtocolSoap< Ttransfertype >\fP\&.
.SS "bool general\&.IProtocol< Ttransfertype >\&.send (Ttransfertypeobj)"

.PP
Implemented in \fBgeneral\&.ProtocolSoap< Ttransfertype >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sharerd-Printing from the source code\&.
