.TH "general.ATopology< Ttransfertype >" 3 "Wed Jun 19 2013" "Sharerd-Printing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
general.ATopology< Ttransfertype > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBgeneral\&.ServerClient< Ttransfertype >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBATopology\fP (IProtocol< Ttransfertype > \fBprotocol\fP)"
.br
.ti -1c
.RI "abstract bool \fBconnect\fP (Ttransfertype obj)"
.br
.ti -1c
.RI "abstract void \fBdisconnect\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP = 'Default Abstract Topology!'"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "IProtocol< Ttransfertype > \fBprotocol\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "general\&.ATopology< Ttransfertype >\&.ATopology (IProtocol< Ttransfertype >protocol)"

.SH "Member Function Documentation"
.PP 
.SS "abstract bool general\&.ATopology< Ttransfertype >\&.connect (Ttransfertypeobj)\fC [pure virtual]\fP"

.PP
Implemented in \fBgeneral\&.ServerClient< Ttransfertype >\fP\&.
.SS "abstract void general\&.ATopology< Ttransfertype >\&.disconnect ()\fC [pure virtual]\fP"

.PP
Implemented in \fBgeneral\&.ServerClient< Ttransfertype >\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string general\&.ATopology< Ttransfertype >\&.name = 'Default Abstract Topology!'"

.SS "IProtocol<Ttransfertype> general\&.ATopology< Ttransfertype >\&.protocol\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sharerd-Printing from the source code\&.
