.TH "general.IPrintTask" 3 "Wed Jun 19 2013" "Sharerd-Printing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
general.IPrintTask \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBgeneral\&.PrintTask\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetPrintTask\fP (string userName, string printName, int printCopies)"
.br
.ti -1c
.RI "String \fBGetUserName\fP ()"
.br
.ti -1c
.RI "void \fBSetUserName\fP (string name)"
.br
.ti -1c
.RI "String \fBGetPrintName\fP ()"
.br
.ti -1c
.RI "void \fBSetPrintName\fP (string name)"
.br
.ti -1c
.RI "int \fBGetCopies\fP ()"
.br
.ti -1c
.RI "void \fBSetCopies\fP (int copies)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int general\&.IPrintTask\&.GetCopies ()"

.PP
Implemented in \fBgeneral\&.PrintTask\fP\&.
.SS "String general\&.IPrintTask\&.GetPrintName ()"

.PP
Implemented in \fBgeneral\&.PrintTask\fP\&.
.SS "String general\&.IPrintTask\&.GetUserName ()"

.PP
Implemented in \fBgeneral\&.PrintTask\fP\&.
.SS "void general\&.IPrintTask\&.SetCopies (intcopies)"

.PP
Implemented in \fBgeneral\&.PrintTask\fP\&.
.SS "void general\&.IPrintTask\&.SetPrintName (stringname)"

.PP
Implemented in \fBgeneral\&.PrintTask\fP\&.
.SS "void general\&.IPrintTask\&.SetPrintTask (stringuserName, stringprintName, intprintCopies)"

.PP
Implemented in \fBgeneral\&.PrintTask\fP\&.
.SS "void general\&.IPrintTask\&.SetUserName (stringname)"

.PP
Implemented in \fBgeneral\&.PrintTask\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sharerd-Printing from the source code\&.
