.TH "general.AComputer< Tprinter, Tuser >" 3 "Wed Jun 19 2013" "Sharerd-Printing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
general.AComputer< Tprinter, Tuser > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBgeneral\&.Computer\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Tprinter[] \fBprinter\fP = new Tprinter[2]"
.br
.ti -1c
.RI "Tuser[] \fBuser\fP = new Tuser[2]"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string general\&.AComputer< Tprinter, Tuser >\&.name"

.SS "Tprinter [] general\&.AComputer< Tprinter, Tuser >\&.printer = new Tprinter[2]"

.SS "Tuser [] general\&.AComputer< Tprinter, Tuser >\&.user = new Tuser[2]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sharerd-Printing from the source code\&.
