.TH "general.Computer" 3 "Wed Jun 19 2013" "Sharerd-Printing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
general.Computer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgeneral\&.AComputer< Tprinter, Tuser >\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sharerd-Printing from the source code\&.
