.TH "general.ServerClient< Ttransfertype >" 3 "Wed Jun 19 2013" "Sharerd-Printing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
general.ServerClient< Ttransfertype > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgeneral\&.ATopology< Ttransfertype >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServerClient\fP (IProtocol< Ttransfertype > \fBprotocol\fP)"
.br
.ti -1c
.RI "override bool \fBconnect\fP (Ttransfertype obj)"
.br
.ti -1c
.RI "override void \fBdisconnect\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "general\&.ServerClient< Ttransfertype >\&.ServerClient (IProtocol< Ttransfertype >protocol)"

.SH "Member Function Documentation"
.PP 
.SS "override bool general\&.ServerClient< Ttransfertype >\&.connect (Ttransfertypeobj)\fC [virtual]\fP"

.PP
Implements \fBgeneral\&.ATopology< Ttransfertype >\fP\&.
.SS "override void general\&.ServerClient< Ttransfertype >\&.disconnect ()\fC [virtual]\fP"

.PP
Implements \fBgeneral\&.ATopology< Ttransfertype >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sharerd-Printing from the source code\&.
