.TH "general.Printer" 3 "Wed Jun 19 2013" "Sharerd-Printing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
general.Printer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MarshalByRefObject, and IPrinter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrinter\fP ()"
.br
.ti -1c
.RI "\fBPrinter\fP (string \fBprinterName\fP)"
.br
.ti -1c
.RI "string \fBGetPrinterName\fP ()"
.br
.ti -1c
.RI "void \fBSetPrinterName\fP (string name)"
.br
.ti -1c
.RI "bool \fBCheckIdle\fP ()"
.br
.ti -1c
.RI "void \fBLoadPrintTask\fP (string printName)"
.br
.ti -1c
.RI "void \fBPrint\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBprinterName\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "general\&.Printer\&.Printer ()"

.SS "general\&.Printer\&.Printer (stringprinterName)"

.SH "Member Function Documentation"
.PP 
.SS "bool general\&.Printer\&.CheckIdle ()"

.SS "string general\&.Printer\&.GetPrinterName ()"

.SS "void general\&.Printer\&.LoadPrintTask (stringprintName)"

.SS "void general\&.Printer\&.Print ()"

.SS "void general\&.Printer\&.SetPrinterName (stringname)"

.SH "Member Data Documentation"
.PP 
.SS "string general\&.Printer\&.printerName"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sharerd-Printing from the source code\&.
