.TH "general" 3 "Wed Jun 19 2013" "Sharerd-Printing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
general \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAComputer< Tprinter, Tuser >\fP"
.br
.ti -1c
.RI "interface \fBIProtocol< Ttransfertype >\fP"
.br
.ti -1c
.RI "class \fBProtocolSoap< Ttransfertype >\fP"
.br
.ti -1c
.RI "class \fBATopology< Ttransfertype >\fP"
.br
.ti -1c
.RI "class \fBServerClient< Ttransfertype >\fP"
.br
.ti -1c
.RI "class \fBComputer\fP"
.br
.ti -1c
.RI "interface \fBIApplication\fP"
.br
.ti -1c
.RI "interface \fBIPrintTask\fP"
.br
.ti -1c
.RI "class \fBPrinter\fP"
.br
.ti -1c
.RI "class \fBPrintTask\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Sharerd-Printing from the source code\&.
