.TH "general.PrintTask" 3 "Wed Jun 19 2013" "Sharerd-Printing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
general.PrintTask \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits MarshalByRefObject, and \fBgeneral\&.IPrintTask\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPrintTask\fP ()"
.br
.ti -1c
.RI "\fBPrintTask\fP (string userName, string printName, int printCopies)"
.br
.ti -1c
.RI "void \fBSetPrintTask\fP (string userName, string printName, int printCopies)"
.br
.ti -1c
.RI "string \fBGetUserName\fP ()"
.br
.ti -1c
.RI "void \fBSetUserName\fP (string name)"
.br
.ti -1c
.RI "string \fBGetPrintName\fP ()"
.br
.ti -1c
.RI "void \fBSetPrintName\fP (string name)"
.br
.ti -1c
.RI "int \fBGetCopies\fP ()"
.br
.ti -1c
.RI "void \fBSetCopies\fP (int copies)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "general\&.PrintTask\&.PrintTask ()"

.SS "general\&.PrintTask\&.PrintTask (stringuserName, stringprintName, intprintCopies)"

.SH "Member Function Documentation"
.PP 
.SS "int general\&.PrintTask\&.GetCopies ()"

.PP
Implements \fBgeneral\&.IPrintTask\fP\&.
.SS "string general\&.PrintTask\&.GetPrintName ()"

.PP
Implements \fBgeneral\&.IPrintTask\fP\&.
.SS "string general\&.PrintTask\&.GetUserName ()"

.PP
Implements \fBgeneral\&.IPrintTask\fP\&.
.SS "void general\&.PrintTask\&.SetCopies (intcopies)"

.PP
Implements \fBgeneral\&.IPrintTask\fP\&.
.SS "void general\&.PrintTask\&.SetPrintName (stringname)"

.PP
Implements \fBgeneral\&.IPrintTask\fP\&.
.SS "void general\&.PrintTask\&.SetPrintTask (stringuserName, stringprintName, intprintCopies)"

.PP
Implements \fBgeneral\&.IPrintTask\fP\&.
.SS "void general\&.PrintTask\&.SetUserName (stringname)"

.PP
Implements \fBgeneral\&.IPrintTask\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sharerd-Printing from the source code\&.
