.TH "general/IApplication.cs" 3 "Wed Jun 19 2013" "Sharerd-Printing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
general/IApplication.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBgeneral\&.IApplication\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBgeneral\fP"
.br
.in -1c
.SS "Constant Groups"

.in +1c
.ti -1c
.RI "package \fBgeneral\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Sharerd-Printing from the source code\&.
