.TH "IPrinter< Ttasktype, Tstate >" 3 "Wed Jun 19 2013" "Sharerd-Printing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPrinter< Ttasktype, Tstate > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBgetType\fP ()"
.br
.ti -1c
.RI "Tstate \fBgetState\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Tstate IPrinter< Ttasktype, Tstate >\&.getState ()"

.SS "string IPrinter< Ttasktype, Tstate >\&.getType ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Sharerd-Printing from the source code\&.
