.TH "Server.Server" 3 "Wed Jun 19 2013" "Sharerd-Printing" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Server.Server \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgeneral\&.IApplication\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServer\fP ()"
.br
.ti -1c
.RI "bool \fBinit\fP ()"
.br
.ti -1c
.RI "bool \fBstart\fP ()"
.br
.ti -1c
.RI "bool \fBstop\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Server\&.Server\&.Server ()"

.SH "Member Function Documentation"
.PP 
.SS "bool Server\&.Server\&.init ()"
Initialize Application object +Do any pre setting up before application starts +Should include things not critical to the creation of the object\&. 
.PP
Implements \fBgeneral\&.IApplication\fP\&.
.SS "bool Server\&.Server\&.start ()"
Start application 
.PP
Implements \fBgeneral\&.IApplication\fP\&.
.SS "bool Server\&.Server\&.stop ()"
Stop application +Should return true on successful stop\&. +Should only stop if application is not busy, in this case return false\&. 
.PP
Implements \fBgeneral\&.IApplication\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Sharerd-Printing from the source code\&.
